apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sLoadBalancerAllowedPorts
metadata:
  name: loadbalancer-allowed-ports
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Service"]
  parameters:
    allowedPorts: {{ .Values.allowedServicePorts }}